B+G E-Tech: Add support for SDM72.
nymea/nymea-plugins-modbus pull request #116
Opened 2023-03-03 16:23 UTC by SebastianRinger

nymea-plugins-modbus pull request checklist:

- [x] Make sure the pull request's title is of format "Plugin name: Add support for xyz" or "New plugin: Plugin name"

- [x] Did you test the changes on hardware, if not (e.g. absence of required hardware), please mention a person to confirm it has been tested.

- [x] Did you update the plugin's README.md accordingly?

- [x] Did you update translations (`cd builddir && make lupdate`)?

Also changed "checkReachableRegister" on SDM630 from current to voltage. Current can be 0 and thus not trigger "value changed" upon reading the register. Voltage is never 0 if the SDM630 has power and can respond to Modbus calls.  
How this came up: Tested a SDM630 and it showed as "not connected", because current was 0.

2023-04-28 10:30 UTC, t-mon requested changes

2023-04-28 10:30 UTC, t-mon commented on bgetech/sdm630-registers.json
> +    "checkReachableRegister": "voltagePhaseA",
is there a reason why you changed this to the voltage?

2023-04-28 10:30 UTC, t-mon commented on bgetech/integrationpluginbgetech.json
> +                            "displayNameEvent": "Connected changed",
all `displayNameEvent` properties are deprecated. The are not required any more.

2023-04-28 10:30 UTC, t-mon commented on bgetech/sdm72-registers.json
> +                }
Looks to me that the only difference to the 630 is the phase energy counters. 
We might consider removing them from the 630 class, or write an own update class skipping that one block...the classes are almost identical and somehow redundant.

2023-05-30 08:41 UTC, mzanetti commented
Closing due to lack of activity

2023-05-30 08:41 UTC, closed without merging