Webasto: Add support fot the Webasto NEXT wallbox
nymea/nymea-plugins-modbus pull request #120
Opened 2023-04-03 10:25 UTC by t-mon

nymea-plugins-modbus pull request checklist:

- [ ] Make sure the pull request's title is of format "Plugin name: Add support for xyz" or "New plugin: Plugin name"

- [ ] Did you test the changes on hardware, if not (e.g. absence of required hardware), please mention a person to confirm it has been tested.

- [ ] Did you update the plugin's README.md accordingly?

- [ ] Did you update translations (`cd builddir && make lupdate`)?

2023-04-28 11:00 UTC, mzanetti commented on webasto/integrationpluginwebasto.cpp
> +    qCDebug(dcWebasto()) << (power ? "Enable": "Disable") << "charging on" << info->thing();
usual debug print nitpick: "Enabling/Disabling..." or it seems to instruct the user to go to the wallbox and do something manually.

2023-05-04 12:03 UTC, t-mon commented on webasto/README.md
> +For communication nymea uses the Modbus TCP connection to connect to the wallbox.
I wanted to prevent starting the snetence with `n`ymea.

2023-05-04 12:10 UTC, t-mon commented on webasto/integrationpluginwebasto.cpp
> +        QHostAddress address = QHostAddress(thing->paramValue(webastoLiveThingIpAddressParamTypeId).toString());
I don't change this without being able to test it. I did that once without testing and it stopped working, not doing it again.

2023-06-06 12:08 UTC, mzanetti requested changes

2023-06-06 12:08 UTC, mzanetti commented on webasto/integrationpluginwebasto.cpp
> +        info->finish(Thing::ThingErrorHardwareNotAvailable, QT_TR_NOOP("The discovery is not available."));
let's start here :)

2023-09-07 10:48 UTC, closed without merging