Mennekes: Add support for the Amtron Compact 2.0
nymea/nymea-plugins-modbus pull request #129
Opened 2023-05-03 17:46 UTC by mzanetti

nymea-plugins-modbus pull request checklist:

- [ ] Make sure the pull request's title is of format "Plugin name: Add support for xyz" or "New plugin: Plugin name"

- [ ] Did you test the changes on hardware, if not (e.g. absence of required hardware), please mention a person to confirm it has been tested.

- [ ] Did you update the plugin's README.md accordingly?

- [ ] Did you update translations (`cd builddir && make lupdate`)?

2023-05-04 12:00 UTC, t-mon requested changes

2023-05-04 12:28 UTC, mzanetti commented on mennekes/integrationpluginmennekes.cpp
> +        connect(discovery, &AmtronCompact20Discovery::discoveryFinished, info, [this, info, discovery](bool modbusMasterAvailable){
Which check? This is in discoverThings(), not setupThing() and I am not sure which check you mean as there is none...

2023-05-04 12:30 UTC, t-mon commented on mennekes/integrationpluginmennekes.cpp
> +        connect(discovery, &AmtronCompact20Discovery::discoveryFinished, info, [this, info, discovery](bool modbusMasterAvailable){
You finish the setup only if you successfully discover the wallbox, which means it must be connectable. I'd do that only if it is the initial setup or a reconfigure

2023-05-04 12:35 UTC, mzanetti commented on mennekes/integrationpluginmennekes.cpp
> +        thing->setStateValue(amtronCompact20ConnectedStateTypeId, success);
fair enough. changed.

2023-05-04 12:52 UTC, t-mon commented on mennekes/integrationpluginmennekes.cpp
> +        connect(discovery, &AmtronCompact20Discovery::discoveryFinished, info, [this, info, discovery](bool modbusMasterAvailable){
sorry, yes, the comment was ment to be in the setup...clicked the wrong line

2023-05-09 17:43 UTC, t-mon approved these changes

2023-05-30 08:43 UTC, mzanetti commented
merged

2023-05-30 08:43 UTC, closed without merging